.\" tinyclipboard - a cross-platform C library for accessing the clipboard.
.\"
.\" Copyright © 2016 Marvin Gülker <m-guelker@guelkerdev.de>
.\"
.\" All rights reserved. See the README and LICENSE files for the
.\" licensing conditions.
.TH tiny_clipwrite "3" "January 2016" "Marvin Gülker" "tinyclipboard"
.SH NAME
tiny_clipwrite \- Write a string to the OS clipboard

.SH SYNOPSIS
.nf
.B #include <tiynclipboard.h>
.sp
.B int tiny_clipwrite\fR(\fBconst char*\fR \fItext\fR);

.SH DESCRIPTION
.PP
Refer to \fBtiny_clipnwrite(3)\fR.

.SH AUTHOR
.PP
The \fItinyclipboard\fR library was written by Marvin Gülker <m-guelker@guelkerdev.de>.
